import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvider from "../providers/AuthProvider";
import ThemeProvider from "@/providers/ThemeProvider";
import SmoothScroll from "@/components/SmoothScroll";
import ReportBugButton from "@/components/ReportBugButton";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = {
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          enableSystem
          disableTransitionOnChange
          defaultTheme="system"
          storageKey="jblog-theme"
        >
          <Toaster
            toastOptions={{
              style: {
                background: "hsl(var(--card))",
                color: "hsl(var(--card-foreground))",
                border: "2px solid hsl(var(--primary))",
                borderRadius: "0.75rem",
                padding: "1.25rem 1.5rem",
                fontSize: "1rem",
                fontWeight: "500",
                minWidth: "300px",
                maxWidth: "500px",
                boxShadow: "0 10px 40px rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.05)",
              },
              success: {
                style: {
                  background: "hsl(var(--card))",
                  color: "hsl(var(--card-foreground))",
                  border: "2px solid hsl(var(--primary))",
                  borderRadius: "0.75rem",
                  padding: "1.25rem 1.5rem",
                  fontSize: "1rem",
                  fontWeight: "500",
                  minWidth: "300px",
                  maxWidth: "500px",
                  boxShadow: "0 10px 40px rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.05)",
                },
                iconTheme: {
                  primary: "hsl(var(--primary))",
                  secondary: "hsl(var(--card))",
                },
              },
              error: {
                style: {
                  background: "hsl(var(--card))",
                  color: "hsl(var(--card-foreground))",
                  border: "2px solid hsl(var(--destructive))",
                  borderRadius: "0.75rem",
                  padding: "1.25rem 1.5rem",
                  fontSize: "1rem",
                  fontWeight: "500",
                  minWidth: "300px",
                  maxWidth: "500px",
                  boxShadow: "0 10px 40px rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.05)",
                },
                iconTheme: {
                  primary: "hsl(var(--destructive))",
                  secondary: "hsl(var(--card))",
                },
              },
              loading: {
                style: {
                  background: "hsl(var(--card))",
                  color: "hsl(var(--card-foreground))",
                  border: "2px solid hsl(var(--primary))",
                  borderRadius: "0.75rem",
                  padding: "1.25rem 1.5rem",
                  fontSize: "1rem",
                  fontWeight: "500",
                  minWidth: "300px",
                  maxWidth: "500px",
                  boxShadow: "0 10px 40px rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.05)",
                },
                iconTheme: {
                  primary: "hsl(var(--primary))",
                  secondary: "hsl(var(--card))",
                },
              },
            }}
            reverseOrder={false}
            position="top-center"
            containerStyle={{
              top: 20,
            }}
          />
          <SmoothScroll>
            <AuthProvider>
              {children}
              <ReportBugButton />
            </AuthProvider>
          </SmoothScroll>
        </ThemeProvider>
      </body>
    </html>
  );
}
